version: '3'

services:
  luigi-scheduler:
    build:
      context: ./datamining-toolbox
      dockerfile: docker/Dockerfile

    command: lud
    ports:
      - 8082:8082
    volumes:
      - ./volumes/luigi-server:/var/lib/luigi-server/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    labels:
      - co.elastic.logs/module=elasticsearch
      - co.elastic.metrics/module=elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

# luigi --module gpn_hack.luigi_tasks.index IndexHH

# luigi.cfg:/app/luigi.cfg

networks:
  default:
    name: gpn_hack
