version: '3'

services:
  luigi-scheduler:
    build:
      context: ./datamining-toolbox
      dockerfile: docker/Dockerfile

    command: lud
    ports:
      - 8082:8082
    volumes:
      - ./volumes/luigi-server:/var/lib/luigi-server/
      - ./luigi.cfg:/app/luigi.cfg
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.app.schedule: "@every 1m"
      ofelia.job-exec.app.command: "/docker-entrypoint.sh lu MainTask"

  elastichq:
    image: elastichq/elasticsearch-hq
    environment:
      HQ_DEFAULT_URL: http://elasticsearch:9200
    ports:
      - 8001:5000

  elasticvue:
    image: cars10/elasticvue
    ports:
      - 8002:8080

  elasticsearch-comrade:
    image: mosheza/elasticsearch-comrade
    ports:
      - 8003:8000
    volumes:
      - ./elasticsearch-comrade-clusters:/app/comrade/clusters/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      http.cors.enabled: "true"
      http.cors.allow-origin: "/.*/"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    labels:
      - co.elastic.logs/module=elasticsearch
      - co.elastic.metrics/module=elasticsearch

  # TODO: страшно флудит в логах
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.14.0
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   environment:
  #     ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    ports:
      - 80:80

networks:
  default:
    name: gpn_hack
